Create base.html and first_page.html
shoishizaki/baseball_game_and_practice_notes_web_app pull request #1
Opened 2019-08-26 17:15 UTC by shoishizaki

@ryotogashi base.htmlとfirst_page.htmlを作成したので確認お願いします。
![image](https://user-images.githubusercontent.com/49173663/63708847-7c5ef100-c870-11e9-9028-e3e99a001e9c.png)

2019-08-26 21:52 UTC, ryonryon approved these changes
👍

2019-08-26 21:55 UTC, ryonryon commented on templates/baseball_game_and_practice_notes/first_page.html
> +  {% extends "base.html" %}
フォルダ内に入れてもいいと思います。

2019-08-26 21:56 UTC, ryonryon requested changes
@shoishizaki 
レビューをしてもらう前に自分の変更ファイル確認しましょう。

2019-08-26 21:56 UTC, ryonryon commented on .idea/workspace.xml
>  <project version="4">
.gitignore 書きましょう。

2019-08-27 04:15 UTC, ryonryon approved these changes
👍

2019-08-27 06:22 UTC, shoishizaki commented
@ryotogashi .gitignoreを作成したので確認お願いします。

2019-08-28 10:31 UTC, merged